name: wms
description: "Warehouse Management System (WMS) for SMP"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
 
version: 1.0.0 

environment:
  sdk: ^3.7.2 

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  path: ^1.8.3 
  open_file: ^3.3.2
  intl: ^0.20.2 
  get: ^4.7.2
  get_storage: ^2.1.1
  qr_flutter: ^4.1.0
  blue_thermal_printer: ^1.2.3 
  cupertino_icons: ^1.0.8
  http: 1.3.0
  flutter_native_splash: ^2.4.4
  firebase_core: ^3.14.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.1.0 
  flutter_launcher_icons: ^0.14.3
  flutter_image_compress: ^2.4.0 
  image: ^4.3.0
  mobile_scanner: ^3.5.3
  dropdown_search: ^5.0.6
  webview_flutter: ^4.2.2
  webview_flutter_android: ^3.10.2
  html_to_image: ^2.0.0
  niimbot_label_printer: ^0.0.2
  permission_handler: ^11.0.1
  printing: ^5.14.2
  pdf: ^3.11.3
  device_info_plus: ^11.5.0
  network_info_plus: ^6.1.4
  encrypt: ^5.0.3
  connectivity_plus: ^6.1.4
  package_info_plus: ^8.3.0
  # qr_code_scanner: ^1.0.1
 
flutter_icons:
  android: true
  ios: true
  image_path: "assets/new_icon.png"
  adaptive_icon_background: "#389CED" # Putih
  adaptive_icon_foreground: "assets/new_icon.png"

# flutter_native_splash:
#   color: "#FFFFFF" # atau warna lain sesuai background app kamu
#   android: true
#   ios: false
#   fullscreen: true 
#   # image: assets/smp.png 

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^5.0.0
 
flutter: 
  uses-material-design: true 
  assets:
    - assets/logo.png 
    - assets/bg.png
    - assets/icon.png
    - assets/splash.png
    - assets/smp.png
    - assets/new_icon.png

   