// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVJvBN-W6v8_G0LLuF1JYfPbjyEmnDvXI',
    appId: '1:192738229033:web:929faed584bfbaa1be9538',
    messagingSenderId: '192738229033',
    projectId: 'wms-apps-92931',
    authDomain: 'wms-apps-92931.firebaseapp.com',
    storageBucket: 'wms-apps-92931.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZY67VxeNEQJS3Gs8hXAlYGablyhcN0ec',
    appId: '1:192738229033:android:001ffc8b6252be14be9538',
    messagingSenderId: '192738229033',
    projectId: 'wms-apps-92931',
    storageBucket: 'wms-apps-92931.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAitOYji7PZxwnMRsMEOelSRu-n9MbHNIU',
    appId: '1:192738229033:ios:ff8ec750b31fc0fabe9538',
    messagingSenderId: '192738229033',
    projectId: 'wms-apps-92931',
    storageBucket: 'wms-apps-92931.firebasestorage.app',
    iosBundleId: 'com.sanymp.wms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAitOYji7PZxwnMRsMEOelSRu-n9MbHNIU',
    appId: '1:192738229033:ios:ff8ec750b31fc0fabe9538',
    messagingSenderId: '192738229033',
    projectId: 'wms-apps-92931',
    storageBucket: 'wms-apps-92931.firebasestorage.app',
    iosBundleId: 'com.sanymp.wms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVJvBN-W6v8_G0LLuF1JYfPbjyEmnDvXI',
    appId: '1:192738229033:web:a0d02115679dc454be9538',
    messagingSenderId: '192738229033',
    projectId: 'wms-apps-92931',
    authDomain: 'wms-apps-92931.firebaseapp.com',
    storageBucket: 'wms-apps-92931.firebasestorage.app',
  );

}