// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhGL0WWcfhSFmtyudSHu_7O3yDV8rccJA',
    appId: '1:408453120849:web:7e9765e025dbdecc658970',
    messagingSenderId: '408453120849',
    projectId: 'dev-wms-mobile',
    authDomain: 'dev-wms-mobile.firebaseapp.com',
    storageBucket: 'dev-wms-mobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9xZooRgl4Z5pN22p0qU1yCDoijQx20DI',
    appId: '1:408453120849:android:6bcdff926d78419a658970',
    messagingSenderId: '408453120849',
    projectId: 'dev-wms-mobile',
    storageBucket: 'dev-wms-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJECa26dJBwMK3Kgtb2SNrYwPki_OTMiM',
    appId: '1:408453120849:ios:74dfd4a888df64d3658970',
    messagingSenderId: '408453120849',
    projectId: 'dev-wms-mobile',
    storageBucket: 'dev-wms-mobile.firebasestorage.app',
    iosBundleId: 'com.sanymp.wms.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJECa26dJBwMK3Kgtb2SNrYwPki_OTMiM',
    appId: '1:408453120849:ios:74dfd4a888df64d3658970',
    messagingSenderId: '408453120849',
    projectId: 'dev-wms-mobile',
    storageBucket: 'dev-wms-mobile.firebasestorage.app',
    iosBundleId: 'com.sanymp.wms.dev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhGL0WWcfhSFmtyudSHu_7O3yDV8rccJA',
    appId: '1:408453120849:web:a0f3aa581a9163f3658970',
    messagingSenderId: '408453120849',
    projectId: 'dev-wms-mobile',
    authDomain: 'dev-wms-mobile.firebaseapp.com',
    storageBucket: 'dev-wms-mobile.firebasestorage.app',
  );
}
